### ISSUE TITLE
Generating QNames with `normalizeUri` fails

### ISSUE THREAD

**Issue by lambdamusic** [RDFLib/rdflib#763] opened 2017-08-16 11:24 UTC
Hello there

I'm trying to generate QNames from URIs using the `namespace_manager.normalizeUri` function, but I ran into some weird behaviour: 

```
In [1]: uri1 = u"http://www.springernature.com/scigraph/things/contributions/b5c40759f52045a0f6e7c73befe3bd74"

In [2]: uri2 = u"http://www.springernature.com/scigraph/things/contributions/980631eef1a62ad91b437f5e50691bff"

In [3]: graph = rdflib.Graph()

In [4]: graph.bind("contributions", rdflib.Namespace("http://www.springernature.com/scigraph/things/contributions/"))

In [5]: graph.namespace_manager.normalizeUri(uri1)
Out[5]: u'contributions:b5c40759f52045a0f6e7c73befe3bd74'

In [6]: graph.namespace_manager.normalizeUri(uri2)
Out[6]: u'<http://www.springernature.com/scigraph/things/contributions/980631eef1a62ad91b437f5e50691bff>'
```

For some unexplained reason, the QName fails with `uri2` even though it's not structurally different from `uri1`.

Looking into the source for `normalizeUri`,  I can see that it relies on `split_uri` so I gave that a shot:

```
In [7]: from rdflib.namespace import split_uri

In [8]: split_uri(uri1)
Out[8]:
(u'http://www.springernature.com/scigraph/things/contributions/',
 u'b5c40759f52045a0f6e7c73befe3bd74')

In [9]: split_uri(uri2)
Out[9]:
(u'http://www.springernature.com/scigraph/things/contributions/980631',
 u'eef1a62ad91b437f5e50691bff')

```

Splitting `uri2` results in a namespace that is longer than expected (it includes the `980631` string).

Is that the cause of the error? Or am I missing something? Thanks in advance for any help.

**Comment by gjhiggins** [comment] 2021-12-26 18:15
Unable to reproduce issue with RDFLib 6.1.1, closing

**Closed by gjhiggins** 2021-12-26 18:15 UTC
