### ISSUE TITLE
Graph comes with a whole lot of unwanted prefixes

### ISSUE THREAD

**Issue by hsolbrig** [RDFLib/rdflib#1676] opened 2022-01-17 17:42 UTC
version 6.1.0 and 6.1.1 come with 40+ pre-packaged prefixes in the Graph.   (example: "brick").  This results in a lot of unwanted prefixes being emitted from tools that serialize graphs in OWL functional, LinkML and other formats.

**Comment by nicholascar** [comment] 2022-01-18 11:37
@hsolbrig could you please show a bit of code that reproduces the error/unwanted behaviour? I struggle a little reproducing this, probably because I'm not using the same serializations you are??

**Comment by nicholascar** [comment] 2022-01-18 12:44
Reproducing error code in https://github.com/RDFLib/rdflib/issues/1679 and closing this Issue as a duplicate of that one.

**Closed by nicholascar** 2022-01-18 12:44 UTC
