### ISSUE TITLE
Endless loop in graph_diff

### ISSUE THREAD

**Issue by yum-yab** [RDFLib/rdflib#1052] opened 2020-05-18 12:45 UTC
Hi,
i tried to diff different versions of ontologies and it worked fine so far, but I encountered [this one](http://purl.bdrc.io/ontology/core/) and it seems it takes forever (stopped it after a few hours) even if i try to diff the same graph object. 

My code is pretty much the example in the docu:

`def graphDiff(oldGraph, newGraph):`
`    oldIsoGraph = compare.to_isomorphic(oldGraph)`
`    newIsoGraph = compare.to_isomorphic(newGraph)`
`    return compare.graph_diff(oldIsoGraph, newIsoGraph)`

**Comment by gjhiggins** [comment] 2021-12-12 11:53
Closing, unable to replicate this specific issue.
```py
def test_graph_diff():
    from rdflib import compare, Graph

    core = Graph()
    core.parse(
        location="http://purl.bdrc.io/ontology/core.owl",
        format="xml",
    )
    admin = Graph()
    admin.parse(
        location="http://purl.bdrc.io/ontology/admin.owl",
        format="xml",
    )
    core_isograph = compare.to_isomorphic(core)
    admin_isograph = compare.to_isomorphic(admin)
    res = compare.graph_diff(core_isograph, admin_isograph)
    print(f"comparison result =\n{res}")

# rdflib:test_issue1052.py:175 comparison result =
# (<Graph identifier=N6242dd5c1b0c496481cdcd65775dcae3 (<class 'rdflib.graph.Graph'>)>,
# <Graph identifier=N22b02edd3d654db6b2e92eba6eba993c (<class 'rdflib.graph.Graph'>)>,
# <Graph identifier=N7fdb20b9c0284ac29a67aabd1225c7a6 (<class 'rdflib.graph.Graph'>)>)
```
Takes a second or two on an i7 laptop.

**Closed by gjhiggins** 2021-12-12 11:53 UTC

**Comment by yum-yab** [comment] 2021-12-13 13:15
Hi @gjhiggins,

sorry for being so unprecise back then. They updated their ontology several times since I submitted this issue, but using [a backup](https://archivo.dbpedia.org/download?o=http%3A//purl.bdrc.io/ontology/core/&f=owl&v=2020.06.10-201820) from that time the issue is reproducible:
```python
def test_graph_diff():
    from rdflib import compare, Graph

    graph1 = Graph()
    graph1.parse(
        location="https://archivo.dbpedia.org/download?o=http%3A//purl.bdrc.io/ontology/core/&f=owl&v=2020.06.10-201820",
        format="xml",
    )
    graph2 = Graph()
    graph2.parse(
        location="https://archivo.dbpedia.org/download?o=http%3A//purl.bdrc.io/ontology/core/&f=owl&v=2020.06.10-201820",
        format="xml",
    )
    graph1_isograph = compare.to_isomorphic(graph1)
    graph2_isograph = compare.to_isomorphic(graph2)
    res = compare.graph_diff(graph1_isograph, graph2_isograph)
    print(f"comparison result =\n{res}")


test_graph_diff()
```
This example uses the same file for both versions, so there should be no difference. But I let it run for roughly 10 min on a modern i7 laptop (using `rdflib==6.0.2`) without any result. Although this version is not official anymore, I think this diff function should never loop that long or at least there should be an option to timeout the `graph_diff` function.

**Comment by gjhiggins** [comment] 2021-12-14 11:54
> They updated their ontology several times since I submitted this issue, but using [a backup](https://archivo.dbpedia.org/download?o=http%3A//purl.bdrc.io/ontology/core/&f=owl&v=2020.06.10-201820) from that time the issue is reproducible:

Thanks for finding that, I can now reproduce the issue. I left it overnight and it was still going this morning :)

> This example uses the same file for both versions, so there should be no difference.  ...  I think this diff function should never loop that long or at least there should be an option to timeout the `graph_diff` function.

To be fair, there is an explicit warning in the documentation ...

> Warning: the time to canonicalize bnodes may increase exponentially on degenerate larger graphs. Use with care!

the key word here is “exponentially”, that's going to hurt and hurt _bad_.

IMO, the ontology that you found is a classic example of what the author means by the term “degenerate larger graph”. It's a bit buried in the RDF/XML but that ontology would appear to present a heavy BNode load and a load of irrelevant (but still costly to process) duplication - quite uncharacteristic of ontologies in general.

It'll be useful to keep around as an example of a degenerate large graph. It doesn't seem to have been published (at that time) as a standalone ontology because the imports are unsatisfiable ...

```
  <rdf:Description rdf:about="">
    <owl:imports rdf:resource="Unknown/"/>
  </rdf:Description>
  <rdf:Description rdf:about="">
    <owl:imports rdf:resource="../roles/ChineseMonastic/"/>
  </rdf:Description>
```
I stripped these out and loaded the ontology into Stanford U's [Protégé](https://protege.stanford.edu/products.php#desktop-protege) (which I strongly recommend for ontology fossicking), saving it out as XML. Serializing the original and the Protégé-saved version as ntriples: there are 5294 triples in the former and only 2985 in the latter. RDFLib's `graph_diff` processes (the non-degenerate) Protégé-saved version vs the current (also non-degenerate) version in under a second.

```
DEBUG    rdflib:test_issue1052.py:45 Diffed in 0.332s,
DEBUG    rdflib:test_issue1052.py:47 In both: 2543
DEBUG    rdflib:test_issue1052.py:49 In first: 69
DEBUG    rdflib:test_issue1052.py:53 In second : 1649
```

Unlike Protégé, RDFLib is deliberately not opinionated w.r.t. graph content (other than format compliance), which is understandable because one valid use-case is that of programmatically cleaning up a degenerate large graph.

I appreciate the suggestion but I think the cost of performing a timeout check deep in the processing ('cos that's the way it would have to happen, given the structure of the implementation) is disproportionate to the relatively minor convenience of not having to kill a process that might, quite reasonably, be taking longer to complete than the user might expect.
