### ISSUE TITLE
requests not included in setup.py

### ISSUE THREAD

**Issue by rob-metalinkage** [RDFLib/rdflib#1122] opened 2020-06-23 03:39 UTC
although requests is defined in  requirements.txt it is not in setup.py and hence not picked up by pip install

**Comment by tgbugs** [comment] 2020-07-20 21:06
It should not be. See https://github.com/RDFLib/rdflib/pull/969 and https://github.com/RDFLib/rdflib/issues/1035. If you need requests install via `pip install rdflib[sparql]`.

**Comment by rob-metalinkage** [comment] 2020-07-20 22:11
See the direction, fair enough...

 but a few things seem off -
1)  there seems to be inconsistency between requirements.txt and setup.py (and not sure if this is a good thing to have similar info in both places anyway?)
2) Parsing a graph from a HTTP request has nothing to do with SPARQL - so this isnt very intuitive a solution
3) probably the parse module should report a sensible error with the correct import suggestion if you ask it for a HTTP source and it doesnt have the install available
4) the documentation for parse is quite explicit HTTP is supported without any mention of the requirement.

I think all these things need to be addressed for the proposed solution to be acceptible.

**Comment by tgbugs** [comment] 2020-07-21 20:40
As I mentioned on the pr, rdflib doesn't use requests for fetching http resources (unless I missed something). If I indeed did not miss something, then we should probably remove requests from requirements.txt since I suspect that @gromgull originally included it for testing purposes, and that is now covered by tests_require.

**Comment by white-gecko** [comment] 2020-08-14 10:22
Isn't the requrements.txt just for development purposes? So in my eyes it is ok that setup.py and requirements.txt are not the same.

**Comment by FlorianLudwig** [comment] 2020-09-07 10:14
@rob-metalinkage 
> Parsing a graph from a HTTP request has nothing to do with SPARQL - so this isnt very intuitive a solution

That is not what `requests` is used for in `rdflib`. It is needed to support service queries, see: [Sparql 1.1 Federated Query Extension](https://www.w3.org/TR/sparql11-federated-query/#service)

@white-gecko Usually the `requiremens.txt` is used for version pinning. Which is important to move towards reproducibility. This means it would:

1. contain exact versions for every package
2. contain all dependencies - including dependencies of dependencies.

Neither is the case with the current files. 

From my experience managing those is somewhat of a PITA. So personally I moved to `pipenv` or `poetry` to manage dependencies.

**Comment by white-gecko** [comment] 2020-09-08 13:59
Ok I did not know that. On the page for `pipenv` it says:

> Managing a requirements.txt file can be problematic, so Pipenv uses the upcoming Pipfile and Pipfile.lock instead, which is superior for basic use cases.

So this might be the future. I assume `poetry` has similar features.

This might be a bigger discussion with @ashleysommer and @nicholascar involved if and how we would like to change the dependency management.

**Comment by nicholascar** [comment] 2020-09-08 19:38
Hi all, I have a PR which I'll put in early next week that removes `requests` from RDFlib. This is possible for in the two places that it's used, its functionality can be replaced with `urllib`.

So this will deal with the immediate issue of having it listed in `setup.py`/`requirements.txt` and is good practice anyway and that PR will close this issue. Whether we move to `poetry` etc is a separate concern (@ashleysommer  and I have briefly talked about it but haven't really done anything there.

**Closed** 2020-10-08 04:00 UTC
