### ISSUE TITLE
Support SPARQL BNode's and property paths at the same time

### ISSUE THREAD

**Issue by tiko-tiko** [RDFLib/rdflib#714] opened 2017-02-12 19:42 UTC
Hi there,

last week I have been building a SPARQL query with some BNode's and property paths in it.
The results differed from what I expected and even some parsing errors occurred.
Unfortunately I had no time to determine the root cause yet, but I compiled a small test suite of the same query expressed in a few variations which I all would expect to succeed.

Regards, tiko-tiko
[bnode-ppath-mix.zip](https://github.com/RDFLib/rdflib/files/769570/bnode-ppath-mix.zip)

**Comment by gromgull** [comment] 2017-02-15 10:20
Thanks for the DAWG test-case files - this is my favourite SPARQL bug format! 

I've added your tests and confirmed they break with master. 

-c is not property path related, I changed it like this: https://github.com/RDFLib/rdflib/blob/d8c6d5239af8275db88094885e33f7bfa18d1f76/test/DAWG/rdflib/bnode-ppath-mix-c.rq 

and the algebra is still wrong: 

```
AskQuery(
    p = Project(
        p = BGP(
            triples = [(rdflib.term.BNode('Ne4ea055e9b884270a95bbfb1cc6f3cef'), rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property')), (rdflib.term.BNode('N8d3aa5601b0345a38953e41a83944d8c'), rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#subClassOf'), rdflib.term.BNode('Ne4ea055e9b884270a95bbfb1cc6f3cef')), (rdflib.term.BNode('Ne4ea055e9b884270a95bbfb1cc6f3cef'), Path(http://www.w3.org/2000/01/rdf-schema#domain / http://www.w3.org/2000/01/rdf-schema#subClassOf / http://www.w3.org/2000/01/rdf-schema#subClassOf), rdflib.term.Variable(u'classF')), (rdflib.term.BNode('Ne4ea055e9b884270a95bbfb1cc6f3cef'), rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#subClassOf'), rdflib.term.Variable(u'classC')), (rdflib.term.Variable(u'property'), rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#range'), rdflib.term.BNode('N8d3aa5601b0345a38953e41a83944d8c'))]
            _vars = set([rdflib.term.Variable(u'property'), rdflib.term.Variable(u'classF'), rdflib.term.Variable(u'classC')])
            )
        PV = [rdflib.term.Variable(u'property'), rdflib.term.Variable(u'classF'), rdflib.term.Variable(u'classC')]
        _vars = set([rdflib.term.Variable(u'property'), rdflib.term.Variable(u'classF'), rdflib.term.Variable(u'classC')])
        )
    datasetClause = []
    PV = [rdflib.term.Variable(u'property'), rdflib.term.Variable(u'classF'), rdflib.term.Variable(u'classC')]
    _vars = set([rdflib.term.Variable(u'property'), rdflib.term.Variable(u'classF'), rdflib.term.Variable(u'classC')])
    )
```

The path ends up with a bnode as subject, although it should be the ?property var :( That means the error is in here somewhere: https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parser.py#L44-L93

**Comment by gromgull** [comment] 2017-02-15 10:46
I don't understand why https://github.com/RDFLib/rdflib/blob/d8c6d5239af8275db88094885e33f7bfa18d1f76/test/DAWG/rdflib/bnode-ppath-mix-f.rq doesn't even parse. 

This somehow IS path related, since it passes if you change it to a normal property.

**Comment by gromgull** [comment] 2017-02-15 11:12
For the parsing error, this: https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parser.py#L500

only allows paths in the first part. That seems odd :( 

Allow it in both makes the query parse, but the test still fails.

**Comment by gromgull** [comment] 2017-02-15 13:09
Confirmed that this was a bug in the SPARQL Grammar: https://www.w3.org/2013/sparql-errata#errata-query-3

Now all failures are the `expandTriples` bug.

**Comment by tiko-tiko** [comment] 2017-02-15 20:00
Oh, sorry I missed that one when tidying up: a412a5bedd3d7278e9b3225f39b64cbdb3eb6de3
I had included a that case to see what is working and what is not.

Good work, finding that grammar bug.

To me it looks like the parser handles the recursive nature of BNodes and interior BNodes are handled in
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parser.py#L73-L74
But then I am missing the part where the interior BNode itself is added as object.
But this hypothesis is not yet tested.

Regards, tiko-tiko

**Comment by tiko-tiko** [comment] 2017-02-15 20:00
Sorry,wrong button

**Comment by tiko-tiko** [comment] 2017-02-16 07:59
Ok, this time with more than a wild guess:
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parser.py#L61
points to res[-3], the subject of the last triple. But
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parser.py#L69
might have added some BNode there.
It should be the root subject res[0].

Regards, tiko-tiko

**Comment by gromgull** [comment] 2017-02-16 08:22
https://github.com/RDFLib/rdflib/commit/a412a5bedd3d7278e9b3225f39b64cbdb3eb6de3

was my bad - I changed it, then comitted the wrong thing :) 

I've made your proposed change in my PR, it works for your queries, lets see what travis says for everything else!

**Comment by gromgull** [comment] 2017-02-16 08:27
That fixed it, I've merged it. Thanks again for a detailed dawg-format bug report, and great debugging!

**Closed by gromgull** 2017-02-16 08:27 UTC
Labels: bug, SPARQL
