### ISSUE TITLE
new version does not parse URL in windows

### ISSUE THREAD

**Issue by yuechenbam** [RDFLib/rdflib#1430] opened 2021-10-10 11:39 UTC
The old version(5) does parse remote URL in windows, however, the new version shows error
"[WinError 123] The syntax for the file name, directory name or disk label is incorrect:" when parse. Is it possible to change it?Thanks

**Comment by yuechenbam** [comment] 2021-10-10 19:27
Thanks for the reply. I simply tried the one in doc and got this error. But it works in rdflib version 5. (I also tried add r'' to it, same result)
<img width="545" alt="bug" src="https://user-images.githubusercontent.com/90606851/136710421-cbe7d447-72d7-487e-88ca-1c75944a0bab.png">

**Comment by wmelder** [comment] 2021-10-12 10:55
I have the same error here on my Windows 10 system with Python 3.7.9 and Rdflib 6.0.1: 
```
OSError: [WinError 123] De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist: '"http:\\www.w3.org\\People\\Berners-Lee\\card"'
```
This is code for the request: 
```
uri = '"http://www.w3.org/People/Berners-Lee/card"'
graph.parse(uri)
```
Evidently, the code prepares a local file URL, where a http URI was intended.

**Comment by nicholascar** [comment] 2021-10-12 12:39
Oh dear, I thought we had solved this in 6.* already…

**Comment by yuechenbam** [comment] 2021-10-12 14:35
Hi. I just tried with the latest version of rdflib, and with Location, and without. The error is the same: "[WinError 123] The syntax for the file name, directory name or disk label is incorrect:"

**Comment by aucampia** [comment] 2021-10-12 15:41
@yuechenbam this is basically what I did in https://github.com/RDFLib/rdflib/pull/1441 - so yes, it can be a solution.

**Comment by Marnellus** [comment] 2021-10-31 06:33
![image](https://user-images.githubusercontent.com/74869816/139571107-f7b2c051-2322-443a-a70e-2ee469457850.png)

This problem seems to persist.

**Comment by nicholascar** [comment] 2021-10-31 08:37
@Marnellus were you testing with `master` or with the latedst RDFlib release (6.0.2)? The fix from PR #1441 won't be in the release, only `master`.

**Comment by aucampia** [comment] 2021-11-02 20:17
Just tested this on windows:

```cmd
PS C:\Users\iwana> pipx run --spec git+https://github.com/RDFLib/rdflib.git@d9e86c9#egg=rdflib python
⚠️  python is already on your PATH and installed at C:\Python310\python.EXE. Downloading and running anyway.
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]'
>>> from rdflib import Graph
>>> g = Graph()
>>> g.parse('http://dbpedia.org/resource/Semantic_Web')
<Graph identifier=Na99d10b48e534cf08b0591130dff22de (<class 'rdflib.graph.Graph'>)>
>>> len(list(g.triples((None,None,None))))
845
```

**Comment by aucampia** [comment] 2021-11-02 20:30
I tried running the test suite on windows though and it is not something that goes down well:

```
PS C:\Users\iwana\d.x\github.com\RDFLib\rdflib> python .\run_tests.py
Running nose with: --attr= test rdflib --where=./ --with-doctest --doctest-extension=.doctest --doctest-tests
C:\Users\iwana\d.x\github.com\RDFLib\rdflib\rdflib\plugins\serializers\nt.py:28: UserWarning: NTSerializer does not use custom encoding.
  warnings.warn("NTSerializer does not use custom encoding.")
.
----------------------------------------------------------------------
Ran 1 test in 0.453s

OK

```

Will maybe look more into it when we are on pytest

**Comment by aucampia** [comment] 2021-11-24 22:11
Once #1478 is merged all tests pass on windows, including the one for this issue.

And once #1471 is merged this should hopefully stay fixed.

**Comment by aucampia** [comment] 2022-01-16 23:09
We have our test suite passing on windows now, and this includes at test for this in `test_graph_http.py`. Are you still experiencing this problem? And if so could you share some more details?

I will close this issue next week if there is nothing further.

**Comment by wmelder** [comment] 2022-01-17 09:39
I checked out the old branch, replaced ```graph.parse(location=uri)``` with ```graph.parse(uri)```, tested it and the results were the same. Therefor, I think this is problem is fixed now.

**Comment by nicholascar** [comment] 2022-01-17 09:43
Sounds like this one is done! I'll close unless we hear back from @yuechenbam in a couple of days.

@wmelder please update to rdflib 6.1.1 if you can! It's got a bunch of improvements on 6.0.1 and even 6.0.2 fixes some JSON-LD issues... We've been making lots of changes in a short time!

**Comment by aucampia** [comment] 2022-01-20 23:59
closing issue as problem is resolved.

**Closed by aucampia** 2022-01-20 23:59 UTC
Labels: bug
