### ISSUE TITLE
ImportError: No module named 'pyMicrodata'

### ISSUE THREAD

**Issue by dbs** [RDFLib/rdflib#574] opened 2016-01-10 18:10 UTC
Under Python 3, invoking the microdata module can throw an uncaught ImportError exception "No module named 'pyMicrodata'", which is rather unexpected for what should be a common operation.

The following currently reproduces the error from the command line:

    rdfpipe -w -i microdata https://ambrose.edu/resources/ambrose-archives

and returns the following traceback:

    Traceback (most recent call last):
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/utils.py", line 297, in __init__
        self.location = urlparse.urljoin(self.data.geturl(),self.headers[URIOpener.CONTENT_LOCATION])
    AttributeError: 'function' object has no attribute 'urljoin'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/bin/rdfpipe", line 9, in <module>
        load_entry_point('rdflib==4.2.1', 'console_scripts', 'rdfpipe')()
      File "/lib/python3.4/site-packages/rdflib/tools/rdfpipe.py", line 181, in main
        outfile, opts.output_format, ns_bindings)
      File "/lib/python3.4/site-packages/rdflib/tools/rdfpipe.py", line 49, in parse_and_serialize
        graph.parse(fpath, format=use_format, **kws)
      File "/lib/python3.4/site-packages/rdflib/graph.py", line 1468, in parse
        location=location, file=file, data=data, **args)
      File "/lib/python3.4/site-packages/rdflib/graph.py", line 1041, in parse
        parser.parse(source, self, **args)
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/structureddata.py", line 306, in parse
        vocab_cache=vocab_cache)
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/structureddata.py", line 252, in _process
        orig_source, graph=graph, rdfOutput=False)
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/__init__.py", line 290, in graph_from_source
        if not rdfOutput : raise e
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/__init__.py", line 262, in graph_from_source
        if not rdfOutput : raise e
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/__init__.py", line 252, in graph_from_source
        input = self._get_input(name)
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/__init__.py", line 204, in _get_input
        url_request = URIOpener(name)
      File "/lib/python3.4/site-packages/rdflib/plugins/parsers/pyMicrodata/utils.py", line 308, in __init__
        from pyMicrodata import MicrodataError
    ImportError: No module named 'pyMicrodata'

**Comment by dbs** [comment] 2016-02-16 16:34
Hmm, I thought that when #578 was merged it would have automatically closed this issue through the semi-magical "Fixes 574" comment but notice now that I missed the "#" in front of the issue number. It was merged into master, and I don't see a 4.2.2 dev branch, so I _think_ this can be closed?

**Comment by joernhees** [comment] 2016-02-17 11:25
master currently is the 4.2.2-dev branch: https://github.com/RDFLib/rdflib/blob/master/rdflib/__init__.py#L48 ...

i'll close this, please reopen if the issue wasn't solved... (can't reproduce)

**Closed by joernhees** 2016-02-17 11:25 UTC
Labels: bug, parsing
