### ISSUE TITLE
rdflib not returning proper sparql result

### ISSUE THREAD

**Issue by noorbakerally** [RDFLib/rdflib#733] opened 2017-04-17 12:26 UTC
I have a sparql query which is

```
Select ?st ?ot ?gt where {
                  {SELECT (count(*) as ?st) where {
                    ?s ?p ?o .
                      FILTER (?s=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                  {SELECT (count(*) as ?ot) where {
                    ?s ?p ?o .
                      FILTER (?o=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                  {SELECT (count(*) as ?gt) where {
                    ?s ?p ?o .
                      FILTER (?o!=<http://vocab.nerc.ac.uk/collection/P08/current/> && ?s!=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                }
```

when I print the result from rdflib, is it `(None, rdflib.term.Literal(u'0', datatype=rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#integer'))`

the result is not valid, because if I run the first subquery only , i.e.

```
SELECT (count(*) as ?st) where {
                    ?s ?p ?o .
                      FILTER (?s=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }
```
I get `(rdflib.term.Literal(u'25', datatype=rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#integer')),)`

Also, if I use Jena to run the first query, i get the values ?st=25, ?ot=0, ?gt=359 which is the valid result, is there any error in my original query but i'm using the exactly same query in Jena ?

Thanks

**Comment by joernhees** [comment] 2017-05-29 17:24
could you provide a minimal example to ease testing?

**Comment by JervenBolleman** [comment] 2019-12-12 14:26
@joernhees I made a test case. However, it does not reproduce the reported bug with current master.

**Comment by nicholascar** [comment] 2020-03-12 04:08
Hi @noorbakerally, @JervenBolleman has produced a test for this via PR #946. Can you confirm that the test is addressing your issue? If it is, it means this issue is irreproducible (it may have been solved in Master branch but not included in the PyPI release). If the issue is irreproducible, we can close this.

**Comment by aucampia** [comment] 2021-06-25 22:37
@noorbakerally just a reminder, would be good to know if you still have this issue.

**Comment by nicholascar** [comment] 2021-06-26 01:36
Downloading the vocabulary used in the original query at <http://vocab.nerc.ac.uk/collection/P08/current/> I get this result for the first query in Jena:

25, 0, 397 - to vocab has increased in size since 2017!

For each query subpart I get 25, 0 & 397 too.

Running the following RDFlib code I get identical results:

```turtle
from rdflib import Graph

g = Graph().parse("/Users/nick/downloads/P08.ttl")
q = """
Select ?st ?ot ?gt where {
                  {SELECT (count(*) as ?st) where {
                    ?s ?p ?o .
                      FILTER (?s=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                  {SELECT (count(*) as ?ot) where {
                    ?s ?p ?o .
                      FILTER (?o=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                  {SELECT (count(*) as ?gt) where {
                    ?s ?p ?o .
                      FILTER (?o!=<http://vocab.nerc.ac.uk/collection/P08/current/> && ?s!=<http://vocab.nerc.ac.uk/collection/P08/current/>)
                  }}
                }
    """
for r in g.query(q):
    print(r)
```

So this error is currently unreproducible. Unless there are any other comments in a couple of days, I'll close this.

**Comment by aucampia** [comment] 2022-05-11 22:36
Closing as there was no further feedback.

**Closed by aucampia** 2022-05-11 22:36 UTC
Labels: bug, SPARQL
