### ISSUE TITLE
SPARQL results missing content_type keyword

### ISSUE THREAD

**Issue by jpmccu** [RDFLib/rdflib#879] opened 2018-11-19 22:49 UTC
All other result types have the content_type keyword, and rdflib/query.py:202 expects it.

https://github.com/RDFLib/rdflib/blob/1503dae6049f0d9b14d9d7f884d8de4cb38b39a3/rdflib/plugins/sparql/results/rdfresults.py#L9

Got the following error when trying to use it in Whyis:

```
  File "/apps/whyis/venv/local/lib/python2.7/site-packages/rdflib/graph.py", line 422, in triples
    for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
  File "/apps/whyis/venv/local/lib/python2.7/site-packages/rdflib/plugins/stores/sparqlstore.py", line 317, in triples
    result = Result.parse(res, format=self.returnFormat)
  File "/apps/whyis/venv/local/lib/python2.7/site-packages/rdflib/query.py", line 202, in parse
    return parser.parse(source, content_type=content_type, **kwargs)
TypeError: <commands.CreateUser object at 0x7fedbe06d490>: parse() got an unexpected keyword argument 'content_type'
```

**Comment by amanbhalla88933** [comment] 2020-05-26 17:48
Hi...Can I work this issue? It seems interesting to me. I would love to communicate with the maintainers regarding the same

**Comment by jimmccusker** [comment] 2020-05-26 20:07
I don't think that anyone needs permission to work on issues. I was able to create a pull request with my first contributions pretty easily. Just be sure to fork the repository, create a branch, and add tests that cover the changes you make. When you think you've addressed the issue, create a pull request.

**Comment by luckyagarwal** [comment] 2020-05-28 11:33
@jimmccusker can you please elaborate the issue further.

**Comment by Akash-Sharma-1** [comment] 2020-05-28 22:33
Hi @jimmccusker !
Is the issue still existing?
Looks like 
` rdflib/plugins/stores/sparqlstore.py", line 317, in triples
    result = Result.parse(res, format=self.returnFormat)`
is no more existing in the current rdflib version.

**Comment by Akash-Sharma-1** [comment] 2020-05-28 22:38
Hi @jimmccusker !
Can this issue still be reproduced? 

It looks like `rdflib/plugins/stores/sparqlstore.py", line 317, in triples result = Result.parse(res, format=self.returnFormat) ` is no more existent in the current rdfLib version.

**Comment by jimmccusker** [comment] 2020-05-28 22:42
This is being called from here:

https://github.com/RDFLib/rdflib/blob/037ea51e5f4863a7f98ff59972fcd34d39a7ed97/rdflib/query.py#L210

And it is being called against this function when the query uses a construct:

https://github.com/RDFLib/rdflib/blob/1503dae6049f0d9b14d9d7f884d8de4cb38b39a3/rdflib/plugins/sparql/results/rdfresults.py#L19

That results in a bad keyword argument of content_type, whereas Graph.parse expects format.

**Comment by gjhiggins** [comment] 2021-12-23 11:14
Fixed in https://github.com/RDFLib/rdflib/commit/302fbf45031cf4e78f7c92cc40122acdc2f0b1ee

**Closed by gjhiggins** 2021-12-23 11:14 UTC
Labels: SPARQL
