### ISSUE TITLE
 Bad syntax error when parse ttl file

### ISSUE THREAD

**Issue by zhang-xh95** [RDFLib/rdflib#2155] opened 2022-11-16 01:37 UTC
when i parse a turtle file using rdflib.parse, it occurs a bad syntax error.
![image](https://user-images.githubusercontent.com/46394627/202061594-8b6a1afc-c182-4ebe-b5d1-b2dea19cba09.png)
![image](https://user-images.githubusercontent.com/46394627/202061715-f4b7f3b3-d5a9-44a1-9320-f4c8b401b52b.png)
I don't get where the error is. Rdflib.parse can support the format like << a b c>> d e?

**Comment by lucascool12** [comment] 2022-12-07 14:56
It seems what you are trying to parse is a turtle-star file. Since rdflib does not support rdf-star as far as I'm aware this rightly so causes an error.

**Comment by aucampia** [comment] 2022-12-11 19:42
@lucascool12 is probably right but in general it is best to include the input so it is easier for us to reproduce.

**Comment by aucampia** [comment] 2023-03-20 21:56
I will close this soon if there is nothing further.

**Comment by Adam-Vandervorst** [comment] 2023-05-22 09:36
Is support for RDF-star planned or in an experimental state somewhere?

**Comment by gjhiggins** [comment] 2023-05-22 11:05
> Is support for RDF-star planned or in an experimental state somewhere?

Support for RDF 1.2 / RDFStar [is planned](https://github.com/RDFLib/rdflib/discussions/2395#discussioncomment-5961102), some experimentation has been done, see [the discussion](https://github.com/RDFLib/rdflib/discussions/1554).

ATM the main consideration is how to handle the amount of work that needs to be done. The situation hasn't much changed since when [gromgull was the only maintainer](https://github.com/RDFLib/rdflib/discussions/1554#discussioncomment-1869988)

**Comment by aucampia** [comment] 2023-05-22 23:23
Closing this as the source is not valid Turtle and is also not supplied.

**Closed by aucampia** 2023-05-22 23:23 UTC
Labels: invalid, marked for closing, works as intended
