### ISSUE TITLE
Update Lexical-to-value mapping for xsd:boolean

### ISSUE THREAD

**Issue by Lars-H** [RDFLib/rdflib#913] opened 2019-05-13 05:25 UTC
Hi,
I think the function for evaluating literals with datatype ```xsd:boolean``` should be updated. 

https://github.com/RDFLib/rdflib/blob/5fa18be1231a5e4dfc86ec28f2f754158c6f6f0b/rdflib/term.py#L1484

Currently, any string which is not equal to "true" or "1" is mapped to "false". However, according to [the spec](https://www.w3.org/TR/xmlschema11-2/#boolean) the lexical space for  boolean is only "0", "1", "true", "false". As a result, in case any other lexical value occurs, the parser should raise an Error and not parse it to a Literal with value "false".

**Comment by arushi019** [comment] 2020-03-31 15:22
Hi! I would like to work on this issue. Please guide me on what changes need to be made to resolve it :) Thanks in advance!

**Comment by white-gecko** [comment] 2020-04-02 13:33
As it seems to me the respective line pointed out by @Lars-H has changed in the meantime:

https://github.com/RDFLib/rdflib/blob/5e691870d242b152a3af09c540bde576ed3aa6c7/rdflib/term.py#L1555

Looking at the code it handles only `true` as true. Maybe best is to first verify the bug still exists by writing a test, that checks for the intended behavior. If the test is successful it would be a good contribution. If it fails it is as well a good contribution and we also look forward to a fix for it.

We are happy about any pull-request helping us to fix bugs.

**Comment by white-gecko** [comment] 2020-04-02 13:49
This somehow collides with the fix introduced in #847 …

**Comment by Lars-H** [comment] 2020-04-02 14:00
Hi,
even if the line is changed as mentioned, the parser still does not raise an Error when invalid strings are passed. 
For example: 
`:a :b "Hello"^^xsd:boolean` 
should not become 
`(URIRef("a"), URIRef("b"), Literal(False))`,
it should raise an Error. 

Cheers,
Lars

**Comment by Lars-H** [comment] 2020-04-02 16:08
The whole datatype situation in RDF is a bit tricky, as for example the use of XSD Datatype is just recommended but not enforced. I support the approach that is currently implemented, where if the value cannot be parsed by the corresponding function, the Literal is still instantiated. However, I think it would be better if this would not be done silently and it would be great to have an option to get warnings when values cannot be parsed to the corresponding Python datatype. Furthermore, not "parseable" Literals should be handled consistently.
For example, consider that I have again the triple `:a :b "Hello"^^xsd:boolean`, with the current parser it will become `False`. If I use this value in an application, I will assume that a valid lexical value was used in the triple. I have no way of tracing that it was "Hello". If on the other hand I have the triple ':a :b "Hello"^^xsd:date', the original lexical value "Hello" is kept in the Literal object. As a result, I can later find that issue of the original RDF data when looking at the Literal value. It is however, not possible for the previous case with `xsd:boolean`.

**Comment by arushi019** [comment] 2020-04-02 16:23
> However, I think it would be better if this would not be done silently and it would be great to have an option to get warnings when values cannot be parsed to the corresponding Python datatype. Furthermore, not "parseable" Literals should be handled consistently.
So instead of error, can we display a warning? I think this should work. 
@white-gecko What do you think about this?

**Comment by arushi019** [comment] 2020-04-02 16:27
> However, I think it would be better if this would not be done silently and it would be great to have an option to get warnings when values cannot be parsed to the corresponding Python datatype.
>
So can we show a warning instead of an error? I think this should work with the existing code.
@white-gecko what do you think?

**Comment by Lars-H** [comment] 2020-04-02 16:48
> > However, I think it would be better if this would not be done silently and it would be great to have an option to get warnings when values cannot be parsed to the corresponding Python datatype.
> 
> So can we show a warning instead of an error? I think this should work with the existing code.
> @white-gecko what do you think?

To implement my suggestions, I think it would require two changes: 
1. Raise an exception if it cannot be parsed to a boolean (i.e., `if not i.lower() in ["1", "0", "true", "false]: raise Exception()`)
https://github.com/RDFLib/rdflib/blob/5e691870d242b152a3af09c540bde576ed3aa6c7/rdflib/term.py#L1555 
2. Do not pass the exception silently here
https://github.com/RDFLib/rdflib/blob/5e691870d242b152a3af09c540bde576ed3aa6c7/rdflib/term.py#L1590-L1594

**Comment by white-gecko** [comment] 2020-04-02 21:27
The comments by @Lars-H lead me to further thoughts. Is it really good to have the whole python datatype system so deep inside the RDFlib? Maybe we should just interpret the abstract syntax of RDF properly in the first place. In a second layer we could transform everything to python datatypes. This would allow to implement things like the SHACL validation as raised in #845 resp. w3c/data-shapes#98 .

Just another case, if I would define a datatype `ex:markdown` or `ex:html` and have a literal `"some text"^^ex:html` we would not check if the value of the literal is actually valid html or render the markdown internally to a html representation.

**Comment by tgbugs** [comment] 2020-04-02 22:48
There are a bunch of existing codebases that depend on that system being so deep inside, so there is probably not an easy way to take it out without causing major hard to debug changes (if I had to guess).

**Comment by arushi019** [comment] 2020-04-03 04:53
> One option for how to deal with this case in particular would be to have a strict version which would raise an error when trying to convert from invalid values for those who need it, and then simply leaving the existing behavior in place.
>
This seems fine as it does not break the existing codebases and makes the user aware of the error. Should I proceed with this approach?

**Comment by arushi019** [comment] 2020-04-05 06:08
I have added the pull request to resolve this issue #995 . Please have a look at it and let me know what changes are needed. Thanks a lot :)

**Comment by white-gecko** [comment] 2020-04-05 17:43
Thank you @arushi019 for your pull-request.

The [RDF 1.1 Concepts and Abstract Syntax (3.3 Literals)](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) is very clear about the whole situation:

> A literal in an RDF graph consists of two or three elements:
> - […] lexical form […]
> - […] datatype IRI […]
> - […] language tag […]
> […]
>
> The literal value associated with a literal is:
> 
> 1.    If the literal is a language-tagged string, then the literal value is a pair consisting of its lexical form and its language tag, in that order.
> 2.    If the literal's datatype IRI is in the set of recognized datatype IRIs, let d be the referent of the datatype IRI.
>    a.     If the literal's lexical form is in the lexical space of d, then the literal value is the result of applying the lexical-to-value mapping of d to the lexical form.
>    b.     Otherwise, the literal is ill-typed and no literal value can be associated with the literal. Such a case produces a semantic inconsistency but is not syntactically ill-formed. Implementations MUST accept ill-typed literals and produce RDF graphs from them. Implementations MAY produce warnings when encountering ill-typed literals.
> 3.    If the literal's datatype IRI is not in the set of recognized datatype IRIs, then the literal value is not defined by this specification.
> 
> Literal term equality: Two literals are term-equal (the same RDF literal) if and only if the two lexical forms, the two datatype IRIs, and the two language tags (if any) compare equal, character by character. Thus, two literals can have the same value without being the same RDF term. For example:
> 
>       "1"^^xs:integer
>       "01"^^xs:integer
>     
> 
> denote the same value, but are not the same literal RDF terms and are not term-equal because their lexical form differs.

We can not fail in the case of an ill-typed literal. We need to produce a value if possible. We have to keep the lexical form in the Literal object for comparison or things like the SHACL use case.

As of #913 0 and 1 are introduced into the lexical space again and a warning is produced. But still any non "true" or "1" lexical-form will produce a False value.

**Comment by white-gecko** [comment] 2020-04-07 07:59
This issue is partially fixed by #995 so I reopen this issue.

**Comment by arushi019** [comment] 2020-04-07 08:38
Hi! What are the remaining problems that need to be solved in this issue?

**Comment by white-gecko** [comment] 2020-04-07 08:58
We would need to extend the Literal calls to contain the lexical-form as well as the value. And the value should not be set in cases of ill-formed lexical-forms.

**Comment by arushi019** [comment] 2020-04-07 09:27
So in case of ill-formed lexical forms, we can return None from the _parseBoolean function but this None would have to be handled at other places as well. How should we go about this?

**Comment by white-gecko** [comment] 2020-04-07 09:34
I think we have to identify these other places. Since this is clearly a breaking change, I have set the milestone for this now to 6.0.0.

**Comment by arushi019** [comment] 2020-04-07 09:41
Okay, I will try and find where we need to handle the None case and get back to you on this shortly. Thanks a lot :)

**Comment by arushi019** [comment] 2020-05-25 12:06
Hi! I updated the function to return None in case of weird boolean values (and updated the test cases of the same function to check for None), and tested it. The tests passed indicating returning None instead of False in this case would not cause disruption in the library. However, it could break projects that depend on parsing weird boolean. The pull request for this update is #1066. Please review it and let me know what you think.

**Closed** 2020-08-27 03:26 UTC

**Comment by VladimirAlexiev** [comment] 2023-10-19 12:07
@white-gecko 
>  if I would define a datatype ex:markdown or ex:html

- `rdf:HTML` is a standard datatype
- `http://ns.ontowiki.net/SysOnt/Markdown` is a datatype defined by https://github.com/no-reply/rdf-markdown and used eg in https://documentation.eccenca.com/22.1/explore-and-author/building-a-customized-user-interface/#markdown
