### ISSUE TITLE
Problem with prefixes created for URIs containing %20

### ISSUE THREAD

**Issue by Aleksander-Drozd** [RDFLib/rdflib#801] opened 2017-12-19 18:16 UTC
The result of runnig this code
```python
from rdflib import Namespace, Graph, BNode, Literal

graph = Graph()
namespace = Namespace('http://example.org/')
graph.bind('', namespace)
node = BNode()

graph.add((node, namespace['first%20name'], Literal('John')))
print(graph.serialize(format='turtle').decode())
```
is
```
@prefix : <http://example.org/> .
@prefix ns1: <http://example.org/first%20> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

[] ns1:name "John" .
```
I expect that triple would be displayed as 
```
[] :first%20name "John" .
```

**Comment by joernhees** [comment] 2017-12-20 10:12
this is not a bug but a feature... (i agree that it's confusing, but it would break a lot of things in XML otherwise).

The reason for the behavior you see is that QNames and CURIEs restict the allowed amount of characters in the so called `LocalPart` a lot more than one would think. The reason is that they are intended to be valid XML attribute names. In other words: `<foo :first%20name="something" />` wouldn't work, cause the `%` is not allowed in that place.

Here's the spec: https://www.w3.org/TR/REC-xml-names/#ns-qualnames
Clicking through you'll arrive at https://www.w3.org/TR/REC-xml/#NT-Name ...

`hex(ord('%')) == '0x25'` is simply not in the char ranges allowed by NameChar.

I'll close this for now, feel free to reopen.

**Comment by joernhees** [comment] 2017-12-20 10:31
on second thought i'll re-open this as Turtle as of RDF 1.1 actually allows such chars in [PrefixedName](https://www.w3.org/TR/turtle/#grammar-production-PrefixedName) via [PN_LOCAL](https://www.w3.org/TR/turtle/#grammar-production-PN_LOCAL).

I can only guess that this (as so many other issues) has a historical reason or is due to the interplay of N3, TTL, NT...

As the serialization is not really wrong (just a little more cryptic than it needs to be), i'll give this low prio... if anyone else wants to investigate the origin and how to solve this (in a backwards compatible way), feel free

**Comment by Aleksander-Drozd** [comment] 2017-12-20 16:34
I will just add that in [test files](https://github.com/w3c/csvw/tree/gh-pages/tests) defied for applications implementing W3C [CSV to RDF conversion](https://www.w3.org/TR/2015/REC-csv2rdf-20151217/) recommendation, there are examples containing '%', e.g. https://github.com/w3c/csvw/blob/gh-pages/tests/test009.ttl

**Comment by aayush17002** [comment] 2020-03-27 10:25
I would like to resolve the issue

**Comment by white-gecko** [comment] 2020-03-27 11:47
@aayush17002 you are welcome. The best is, if you create a pull-request and refer to this issue in the pull-request description. We can then discuss if we want to introduce it in 5.0.0 or a later release.

**Comment by aayush17002** [comment] 2020-05-10 08:42
I have provided a solution to solve the above problem. I would like you to review the solution and revert back.

**Closed** 2020-07-30 05:10 UTC
Labels: discussion, enhancement, good first issue, help wanted, low prio, serialization
