### ISSUE TITLE
Failed to parse Turtle URL ending with a dot

### ISSUE THREAD

**Issue by sharpaper** [RDFLib/rdflib#933] opened 2019-09-13 12:28 UTC
This is valid Turtle syntax

    PREFIX : <http://example.org/>
    :0A\.D\. :key :value .

but RDFLib is failing to parse it. It does not parse the second dot in `:0A\.D\.`

How to reproduce:

    #!/usr/bin/env python3
    
    from rdflib import Graph
    
    data = """
    PREFIX : <http://example.org/>
    :0A\.D\. :key :value .
    """
    
    node = Graph()
    node.parse(data=data, format="turtle")

And the error message:

    rdflib.plugins.parsers.notation3.BadSyntax: at line 4 of <>:
    Bad syntax (objectList expected) at ^ in:
    "b'\nPREFIX : <http://example.org/>\n\n:0A\\.D\\. :key :value'^b' .\n'"

Is this a bug or am I doing something wrong?

**Comment by Tanish-Gupta** [comment] 2020-05-25 19:59
Is this still an issue?

**Comment by luckyagarwal** [comment] 2020-05-28 11:12
@sharpaper So this is not a bug. if you do the following modification in your input stream to the node.parse() it fixes the issue.
```python
from rdflib import Graph

data = """
PREFIX : <http://example.org/>
:0A\.D\. :key\. :value .
"""
```

**Comment by sanyam19106** [comment] 2020-05-29 15:40
from rdflib import Graph
data="""
PREFIX : <http://example.org/>
:0A\.D\. :key . :value .
"""
g = ConjunctiveGraph()
g.parse(data=data, format="turtle")

In the data file  missing the "." after the key because :0A\.D\ . is the a triple  which has only subject not a predicate and object  so that every triples ends with the "." (dot) ,similarly :key is also a triple which has no predicate and object so we need to put "." after the :key .

**Comment by gjhiggins** [comment] 2021-12-26 22:28
Not actually an issue, closing.

**Closed by gjhiggins** 2021-12-26 22:28 UTC
