### ISSUE TITLE
wheels for rdflib

### ISSUE THREAD

**Issue by srkunze** [RDFLib/rdflib#520] opened 2015-09-03 23:33 UTC
Hi. Do you consider providing wheels for rdflib? http://pythonwheels.com/

**Comment by joernhees** [comment] 2015-09-04 11:56
duplicate of #478

**Closed by joernhees** 2015-09-04 11:56 UTC

**Comment by srkunze** [comment] 2015-09-04 14:06
Thanks. :) Why the heck didn't I find it when I searched for wheels? -.-
