### ISSUE TITLE
Trig serialisation handling prefixes incorrectly

### ISSUE THREAD

**Issue by dschallis** [RDFLib/rdflib#428] opened 2014-10-15 13:18 UTC
In version 4.1.2 (under python 2.7), running the Trig test detailed at https://github.com/RDFLib/rdflib/issues/317 produces invalid Trig output.

Running the code:

```
from rdflib import ConjunctiveGraph

data = """
@prefix ns1: <http://chartex.org/chartex-schema#> .
<http://chartex.org/graphid/document1> = {
    ns1:Person_A a ns1:Person ;
        ns1:TextSpan "Simon" .
    ns1:Person_B a ns1:Person ;
        ns1:TextSpan "Walter" .
}
<http://chartex.org/graphid/document2> = {
    ns1:Person_C a ns1:Person ;
        ns1:TextSpan "Agnes" .
    ns1:Person_D a ns1:Person ;
        ns1:TextSpan "Emma" .
}
<http://chartex.org/graphid/Person_Atenant_ofPerson_B> = {
    ns1:Person_A ns1:tenant_of ns1:Person_B .
}
<http://chartex.org/graphid/Person_Ctenant_ofPerson_D> = {
    ns1:Person_C ns1:tenant_of ns1:Person_D .
}
<http://chartex.org/graphid/ConfidenceMetrics> = {
    <http://chartex.org/graphid/Person_Atenant_ofPerson_B> ns1:confidence 0.9265 .
    <http://chartex.org/graphid/Person_Ctenant_ofPerson_D> ns1:confidence 0.8765 .
}
"""

cg = ConjunctiveGraph()
cg.parse(data=data, format='trig')
print cg.serialize(format='trig')
```

produces the invalid Trig output:

```
@prefix ns1: <http://chartex.org/chartex-schema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<ns2:Person_Atenant_ofPerson_B> = {
    ns1:Person_A ns1:tenant_of ns1:Person_B .
}

<ns2:ConfidenceMetrics> = {
    ns2:Person_Atenant_ofPerson_B ns1:confidence 0.9265 .

    ns2:Person_Ctenant_ofPerson_D ns1:confidence 0.8765 .
}

<ns2:Person_Ctenant_ofPerson_D> = {
    ns1:Person_C ns1:tenant_of ns1:Person_D .
}

<ns2:document2> = {
    ns1:Person_C a ns1:Person ;
        ns1:TextSpan "Agnes" .

    ns1:Person_D a ns1:Person ;
        ns1:TextSpan "Emma" .
}

<ns2:document1> = {
    ns1:Person_A a ns1:Person ;
        ns1:TextSpan "Simon" .

    ns1:Person_B a ns1:Person ;
        ns1:TextSpan "Walter" .
}
```

The Trig output contains the prefix "ns2" for graphs, but this prefix isn't defined anywhere. In addition, the prefixed graph name shouldn't be enclosed within angle brackets, e.g. the correct output for each named graph should be either:

```
@prefix ns2: <http://chartex.org/graphid/> .

ns2:document1 = {
    ...
}
```

Or:

```
<http://chartex.org/graphid/document1> = {
    ...
}
```

**Comment by RinkeHoekstra** [comment] 2015-04-17 09:19
I just stumbled upon the same problem, and the problem occurs when the TurtleSerializer serializes a IRI that does not belong to a known namespace. This namespace is then created based on some quesswork, but because the TrigSerializer has by that point already serialized the namespace declaration  (the turtle serializer is essentially called for every graph in the store), the newly added namespace is not picked up properly.

For now my workaround is just to serialize the graph twice in succession.

**Comment by drewp** [comment] 2015-07-21 08:36
I was running into something like this. These patches may help:
https://github.com/drewp/rdflib/commit/5d9a7b05b223a08028d0a7899789b5259741cb5a
https://github.com/drewp/rdflib/commit/bd57db75f14e20aa7330624b671fb2160587dbd8
https://github.com/drewp/rdflib/commit/f167ecf880ea48490c0ecc3e61103e784c42438a

I don't remember why I was doing these or why I stopped trying to get them merged back.

**Comment by white-gecko** [comment] 2016-06-07 12:26
Regarding the workaround of @RinkeHoekstra still the issue is, that qnames are generated, but printed in `<…>`

**Comment by gromgull** [comment] 2017-01-24 12:22
this works fine in master now.

**Closed by gromgull** 2017-01-24 12:22 UTC
