### ISSUE TITLE
rdflib under  python3

### ISSUE THREAD

**Issue by pfps** [RDFLib/rdflib#617] opened 2016-04-09 13:07 UTC
Is rdflib supposed to work in python3?

I´m getting one of the canonical non-compatability errors when I run its SPARQL implementation in python3.

Here is an edited version of what I am seeing, with some test printout included:

``` python
...
SORTING [((2, -4, True), (rdflib.term.Variable('this'), rdflib.term.URIRef('http://www.w3.org/ns/shacl#p1'), rdflib.term.Variable('value1'))), 
     ((2, -4, True), (rdflib.term.Variable('this'), Path(http://www.w3.org/ns/shacl#p2 / http://www.w3.org/ns/shacl#p2), rdflib.term.Variable('value1')))]
Traceback (most recent call last):
...
  File "/usr/lib/python3.4/site-packages/rdflib/graph.py", line 1084, in query
    query_object, initBindings, initNs, **kwargs))
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/processor.py", line 73, in query
    query = translateQuery(parsetree, base, initNs)
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 746, in translateQuery
    P, PV = translate(q[1])
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 535, in translate
    M = translateGroupGraphPattern(q.where)
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 295, in translateGroupGraphPattern
    G = Join(p1=G, p2=translateGroupOrUnionGraphPattern(p))
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 244, in translateGroupOrUnionGraphPattern
    g = translateGroupGraphPattern(g)
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 267, in translateGroupGraphPattern
    return ToMultiSet(translate(graphPattern)[0])
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 535, in translate
    M = translateGroupGraphPattern(q.where)
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 280, in translateGroupGraphPattern
    g[-1]["triples"] += triples(p.triples)
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 133, in triples
    for x in range(0, len(l), 3))
  File "/usr/lib/python3.4/site-packages/rdflib/plugins/sparql/algebra.py", line 115, in reorderTriples
    1], varsknown, varscount), x[1]) for x in l[i:])
TypeError: unorderable types: SequencePath() < URIRef()
```

The query includes SPARQL path expressions and these seem to be involved in
the comparison.

**Comment by joernhees** [comment] 2016-04-10 12:12
yupp, rdflib is meant to work in py3...

can you provide a few lines of code that lead to that error, so i could try to reproduce with the latest dev version?

**Comment by pfps** [comment] 2016-04-11 11:28
OK.  Here is a small file.  The first two queries are OK but the last two fail.  It appears that the culprit is trying to sort sequence paths so the solution is going to be to implement sorting for them.  The error that I get is along the lines of
TypeError: unorderable types: SequencePath() < URIRef()

[I'm again having problems uploading.]

**Comment by pfps** [comment] 2016-04-11 11:33
Here is the file, as I can't seem to upload.

import rdflib

g = rdflib.Graph()

print("QUERY 0")
query = """
    SELECT  ?this
    WHERE {
          ?this <http://www.w3.org/ns#p2> ?value1 .
          ?this <http://www.w3.org/ns#p2> ?value1 .
       }
  """
g.query(query)

print("QUERY 1")
query = """
    SELECT  ?this
    WHERE {
          ?this <http://www.w3.org/ns#p1>/<http://www.w3.org/ns#p2> ?value1 .
       }
  """
g.query(query)

print("QUERY 2")
query = """
    SELECT  ?this
    WHERE {
          ?this <http://www.w3.org/ns#p1> ?value1 . 
          ?this <http://www.w3.org/ns#p2>/<http://www.w3.org/ns#p2> ?value1 .
       }
  """
g.query(query)

print("QUERY 3")
query = """
    SELECT  ?this
    WHERE {
          ?this <http://www.w3.org/ns#p2>/<http://www.w3.org/ns#p2> ?value1 .
          ?this <http://www.w3.org/ns#p1>/<http://www.w3.org/ns#p2> ?value1 .
       }
  """
g.query(query)

**Comment by joernhees** [comment] 2016-05-10 13:59
as an alternative to uploading files, just copy & paste short python code snippets into a blocks like this in future (looks better and is easier to access anyhow):

    ```python
    your code here
    ```

i labelled your reports and reformatted them, so they won't be forgotten... if someone is less busy and searching for some in-depth SPARQL knowledge: dive in ;)

**Comment by pjohnston-wiley** [comment] 2016-07-01 16:33
It's just because rdflib.paths.SequencePath doesn't support sort comparisons. You can make this work in your own code by inserting the following (mickey mouse sort by string comparison):

```python
# Egregious hack, the SequencePath object doesn't support compare, this implements the __lt__ method so that algebra.py works on sorting in SPARQL queries on e.g. rdf:List paths
def sequencePathCompareLt(self, other):
    return str(self) < str(other)

def sequencePathCompareGt(self, other):
    return str(self) < str(other)

setattr(SequencePath, '__lt__', sequencePathCompareLt)
setattr(SequencePath, '__gt__', sequencePathCompareGt)
# End egregious hack
```

It's not particularly meaningful other than making code work, but it could go into `sequence.py` as:

```python
class SequencePath(Path):
...
  def __lt__ (self, other):
    return str(self) < str(other)
  def __gt__ (self, other):
    return str(self) > str(other)
...
```

I am sure there is a more intelligent sort to implement, but this will work.

**Comment by gromgull** [comment] 2017-01-19 11:08
related: https://github.com/RDFLib/rdflib/issues/653

not sure why https://github.com/RDFLib/rdflib/commit/57e8f7173d95047d4fa71dc4c684aaa0fd6c15a9 / https://github.com/RDFLib/rdflib/commit/25bfa5bd1f200dae993cddf21cc8726d6db00c63 did fix :(

**Comment by gromgull** [comment] 2017-01-19 11:15
actually - for me the code in https://github.com/RDFLib/rdflib/issues/617#issuecomment-208299414 runs without error on HEAD.

**Comment by gromgull** [comment] 2017-01-19 11:16
I'm going to @pjohnston-wiley used 4.2.1 where it's broken, and it's now fixed in master :) 

reopen if I'm wrong!

**Closed by gromgull** 2017-01-19 11:16 UTC
Labels: bug, SPARQL, up-for-grabs
